name: CI

on:
  push:
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.16.3'
    - name: Install dependencies
      run: |
        go version
        go get -u golang.org/x/lint/golint
    - name: Run cross build
      run: script/build.sh
    # Run vet on the code
    - name: Run vet
      run: go vet .
    
    # Run testing on the code
    # - name: Run testing
    #   run: cd test && go test -v
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: target/*.deb
