name: CI

env:
  BINARY_NAME: instance-tag-discovery-linux

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"

      - name: Run tests
        run: go test .
      - name: Vet
        run: go vet .
  upload:
    runs-on: ubuntu-latest
    needs: [test]
    if: github.ref == 'refs/heads/main'

    # Required by aws-actions/configure-aws-credentials
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.17"
      - name: Build
        run: |
          GOOS=linux GOARCH=arm64 go build -o $BINARY_NAME-arm64 main.go
          GOOS=linux GOARCH=amd64 go build -o $BINARY_NAME-amd64 main.go

      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - uses: guardian/actions-riff-raff@main
        with:
          app: instance-tag-discovery
          stack: deploy
          deployments: |
            instance-tag-discovery:
              type: aws-s3
              sources: ${{ env.BINARY_NAME }}-arm64,${{ env.BINARY_NAME }}-amd64
              parameters:
                bucket: amigo-data
                cacheControl: private
                publicReadAcl: false
